In [1]:
# 12球団の打撃成績を10年分（2014年から2023年）集める
# ライブラリの読み込み

import pandas as pd

In [2]:
# 2023パリーグ
url_23p = 'https://npb.jp/bis/2023/stats/tmb_p.html'
df_23p = pd.read_html(url_23p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_23p['年度'] = 2023

# 確認
df_23p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,オリックス,0.250,143,5324,4782,508,1194,211,17,109,...,83,25,371,8,63,986,106,0.369,0.311,2023
1,ソフトバンク,0.248,143,5454,4786,536,1185,195,15,104,...,107,38,470,14,53,1053,88,0.360,0.319,2023
2,楽 天,0.244,143,5369,4667,513,1140,168,25,104,...,125,33,490,9,52,937,108,0.358,0.321,2023
3,ロッテ,0.239,143,5414,4744,505,1135,220,12,100,...,116,39,453,20,62,1011,79,0.354,0.311,2023
4,西 武,0.233,143,5222,4672,435,1088,188,21,90,...,90,28,387,9,45,1045,97,0.340,0.296,2023
5,日本ハム,0.231,143,5248,4688,464,1082,195,18,100,...,84,25,397,10,54,1111,78,0.344,0.297,2023

In [3]:
# 2023セリーグ
url_23c = 'https://npb.jp/bis/2023/stats/tmb_c.html'
df_23c = pd.read_html(url_23c)[0]
df_23c['年度'] = 2023

# 確認
df_23c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,巨 人,0.252,143,5352,4826,523,1218,204,14,164,...,93,31,365,38,37,1111,94,0.402,0.308,2023
1,DeNA,0.247,143,5331,4783,520,1182,230,18,105,...,106,31,355,22,56,846,103,0.369,0.305,2023
2,阪 神,0.247,143,5479,4775,555,1180,179,34,84,...,106,47,494,35,57,1173,92,0.352,0.322,2023
3,広 島,0.246,143,5241,4728,493,1165,197,18,96,...,96,20,349,25,48,1032,115,0.357,0.304,2023
4,ヤクルト,0.239,143,5358,4712,534,1128,212,11,123,...,115,34,447,23,50,1096,112,0.367,0.310,2023
5,中 日,0.234,143,5251,4792,390,1123,186,19,71,...,92,22,306,18,39,1029,97,0.326,0.285,2023

In [4]:
# とりあえず2023のセパを結合してみる
df_23 = pd.concat([df_23p, df_23c], axis=0, ignore_index=True)
df_23

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,オリックス,0.250,143,5324,4782,508,1194,211,17,109,...,83,25,371,8,63,986,106,0.369,0.311,2023
1,ソフトバンク,0.248,143,5454,4786,536,1185,195,15,104,...,107,38,470,14,53,1053,88,0.360,0.319,2023
2,楽 天,0.244,143,5369,4667,513,1140,168,25,104,...,125,33,490,9,52,937,108,0.358,0.321,2023
3,ロッテ,0.239,143,5414,4744,505,1135,220,12,100,...,116,39,453,20,62,1011,79,0.354,0.311,2023
4,西 武,0.233,143,5222,4672,435,1088,188,21,90,...,90,28,387,9,45,1045,97,0.340,0.296,2023
5,日本ハム,0.231,143,5248,4688,464,1082,195,18,100,...,84,25,397,10,54,1111,78,0.344,0.297,2023
6,巨 人,0.252,143,5352,4826,523,1218,204,14,164,...,93,31,365,38,37,1111,94,0.402,0.308,2023
7,DeNA,0.247,143,5331,4783,520,1182,230,18,105,...,106,31,355,22,56,846,103,0.369,0.305,2023
8,阪 神,0.247,143,5479,4775,555,1180,179,34,84,...,106,47,494,35,57,1173,92,0.352,0.322,2023
9,広 島,0.246,143,5241,4728,493,1165,197,18,96,...,96,20,349,25,48,1032,115,0.357,0.304,2023
10,ヤクルト,0.239,143,5358,4712,534,1128,212,11,123,...,115,34,447,23,50,1096,112,0.367,0.310,2023
11,中 日,0.234,143,5251,4792,390,1123,186,19,71,...,92,22,306,18,39,1029,97,0.326,0.285,2023

In [5]:
# 手間はかかるが、一気にやるのは怖いので、
# 年度ごとにセパ結合してから10年分結合
# 2022パ

url_22p = 'https://npb.jp/bis/2022/stats/tmb_p.html'
df_22p = pd.read_html(url_22p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_22p['年度'] = 2022

# 確認
df_22p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,ソフトバンク,0.255,143,5384,4772,555,1218,189,34,108,...,110,31,420,10,51,1096,88,0.377,0.320,2022
1,オリックス,0.246,143,5379,4723,490,1164,220,26,89,...,114,35,425,26,80,987,98,0.361,0.317,2022
2,楽 天,0.243,143,5458,4738,533,1150,179,29,101,...,95,30,535,13,60,1063,99,0.357,0.325,2022
3,日本ハム,0.234,143,5177,4661,463,1091,214,26,100,...,98,27,352,18,39,1148,67,0.356,0.292,2022
4,ロッテ,0.231,143,5300,4655,501,1075,196,15,97,...,94,47,433,11,69,1052,95,0.342,0.303,2022
5,西 武,0.229,143,5201,4633,464,1062,191,25,118,...,78,27,426,19,37,1095,93,0.358,0.298,2022

In [6]:
# 2022セ
url_22c = 'https://npb.jp/bis/2022/stats/tmb_c.html'
df_22c = pd.read_html(url_22c)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_22c['年度'] = 2022

# 確認
df_22c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,広 島,0.257,143,5394,4865,552,1248,200,25,91,...,118,31,327,20,53,980,112,0.364,0.309,2022
1,DeNA,0.251,143,5275,4746,497,1190,228,12,117,...,102,22,351,30,54,932,109,0.378,0.308,2022
2,ヤクルト,0.250,143,5446,4834,619,1209,210,20,174,...,86,29,442,34,55,1118,102,0.410,0.318,2022
3,中 日,0.247,143,5284,4750,414,1172,208,27,62,...,123,30,323,21,57,956,92,0.341,0.301,2022
4,阪 神,0.243,143,5323,4767,489,1160,152,21,84,...,119,32,358,21,47,1020,90,0.337,0.301,2022
5,巨 人,0.242,143,5341,4788,548,1161,199,14,163,...,73,15,429,25,36,1062,89,0.392,0.309,2022

In [7]:
# 22年結合
df_22 = pd.concat([df_22p, df_22c], axis=0, ignore_index=True)
df_22

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,ソフトバンク,0.255,143,5384,4772,555,1218,189,34,108,...,110,31,420,10,51,1096,88,0.377,0.320,2022
1,オリックス,0.246,143,5379,4723,490,1164,220,26,89,...,114,35,425,26,80,987,98,0.361,0.317,2022
2,楽 天,0.243,143,5458,4738,533,1150,179,29,101,...,95,30,535,13,60,1063,99,0.357,0.325,2022
3,日本ハム,0.234,143,5177,4661,463,1091,214,26,100,...,98,27,352,18,39,1148,67,0.356,0.292,2022
4,ロッテ,0.231,143,5300,4655,501,1075,196,15,97,...,94,47,433,11,69,1052,95,0.342,0.303,2022
5,西 武,0.229,143,5201,4633,464,1062,191,25,118,...,78,27,426,19,37,1095,93,0.358,0.298,2022
6,広 島,0.257,143,5394,4865,552,1248,200,25,91,...,118,31,327,20,53,980,112,0.364,0.309,2022
7,DeNA,0.251,143,5275,4746,497,1190,228,12,117,...,102,22,351,30,54,932,109,0.378,0.308,2022
8,ヤクルト,0.250,143,5446,4834,619,1209,210,20,174,...,86,29,442,34,55,1118,102,0.410,0.318,2022
9,中 日,0.247,143,5284,4750,414,1172,208,27,62,...,123,30,323,21,57,956,92,0.341,0.301,2022
10,阪 神,0.243,143,5323,4767,489,1160,152,21,84,...,119,32,358,21,47,1020,90,0.337,0.301,2022
11,巨 人,0.242,143,5341,4788,548,1161,199,14,163,...,73,15,429,25,36,1062,89,0.392,0.309,2022

In [8]:
# 2021パ

url_21p = 'https://npb.jp/bis/2021/stats/tmb_p.html'
df_21p = pd.read_html(url_21p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_21p['年度'] = 2021

# 確認
df_21p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,オリックス,0.247,143,5258,4694,551,1160,178,19,133,...,80,30,384,21,70,962,104,0.378,0.312,2021
1,ソフトバンク,0.247,143,5298,4688,564,1157,201,26,132,...,93,38,452,20,27,1066,80,0.385,0.314,2021
2,楽 天,0.243,143,5386,4641,532,1129,178,27,108,...,105,32,538,11,70,975,100,0.363,0.329,2021
3,西 武,0.239,143,5245,4623,521,1107,195,20,112,...,83,46,442,11,51,1006,84,0.363,0.310,2021
4,ロッテ,0.239,143,5329,4612,584,1104,233,17,126,...,106,42,514,16,55,1053,90,0.379,0.320,2021
5,日本ハム,0.231,143,5251,4617,454,1067,203,24,78,...,89,32,468,11,45,1207,93,0.336,0.306,2021

In [9]:
# 2021セ

url_21c = 'https://npb.jp/bis/2021/stats/tmb_c.html'
df_21c = pd.read_html(url_21c)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_21c['年度'] = 2021

# 確認
df_21c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,広 島,0.264,143,5361,4798,557,1265,200,17,123,...,85,34,402,24,42,1015,94,0.389,0.324,2021
1,DeNA,0.258,143,5340,4784,559,1233,254,13,136,...,81,24,407,18,43,1028,107,0.402,0.320,2021
2,ヤクルト,0.254,143,5399,4708,625,1196,214,17,142,...,90,27,513,22,61,1079,105,0.397,0.333,2021
3,阪 神,0.247,143,5265,4704,541,1164,208,23,121,...,82,33,406,22,40,1082,95,0.379,0.311,2021
4,巨 人,0.242,143,5241,4692,552,1137,207,11,169,...,48,27,431,22,43,1157,98,0.399,0.310,2021
5,中 日,0.237,143,5073,4595,405,1090,182,21,69,...,98,23,326,26,31,973,104,0.331,0.291,2021

In [10]:
# 21年結合
df_21 = pd.concat([df_21p, df_21c], axis=0, ignore_index=True)
df_21

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,オリックス,0.247,143,5258,4694,551,1160,178,19,133,...,80,30,384,21,70,962,104,0.378,0.312,2021
1,ソフトバンク,0.247,143,5298,4688,564,1157,201,26,132,...,93,38,452,20,27,1066,80,0.385,0.314,2021
2,楽 天,0.243,143,5386,4641,532,1129,178,27,108,...,105,32,538,11,70,975,100,0.363,0.329,2021
3,西 武,0.239,143,5245,4623,521,1107,195,20,112,...,83,46,442,11,51,1006,84,0.363,0.310,2021
4,ロッテ,0.239,143,5329,4612,584,1104,233,17,126,...,106,42,514,16,55,1053,90,0.379,0.320,2021
5,日本ハム,0.231,143,5251,4617,454,1067,203,24,78,...,89,32,468,11,45,1207,93,0.336,0.306,2021
6,広 島,0.264,143,5361,4798,557,1265,200,17,123,...,85,34,402,24,42,1015,94,0.389,0.324,2021
7,DeNA,0.258,143,5340,4784,559,1233,254,13,136,...,81,24,407,18,43,1028,107,0.402,0.320,2021
8,ヤクルト,0.254,143,5399,4708,625,1196,214,17,142,...,90,27,513,22,61,1079,105,0.397,0.333,2021
9,阪 神,0.247,143,5265,4704,541,1164,208,23,121,...,82,33,406,22,40,1082,95,0.379,0.311,2021
10,巨 人,0.242,143,5241,4692,552,1137,207,11,169,...,48,27,431,22,43,1157,98,0.399,0.310,2021
11,中 日,0.237,143,5073,4595,405,1090,182,21,69,...,98,23,326,26,31,973,104,0.331,0.291,2021

In [11]:
# 2020パ

url_20p = 'https://npb.jp/bis/2020/stats/tmb_p.html'
df_20p = pd.read_html(url_20p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_20p['年度'] = 2020

# 確認
df_20p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,楽 天,0.258,120,4628,3990,557,1029,190,23,112,...,87,30,473,9,48,918,87,0.401,0.341,2020
1,日本ハム,0.249,120,4560,3952,493,986,153,17,89,...,85,31,460,9,32,878,86,0.364,0.330,2020
2,ソフトバンク,0.249,120,4480,3933,531,979,165,28,126,...,81,34,398,13,34,851,50,0.401,0.321,2020
3,オリックス,0.247,120,4467,3947,442,975,166,19,90,...,89,21,361,20,49,811,86,0.367,0.316,2020
4,西 武,0.238,120,4440,3898,479,926,161,24,107,...,60,27,411,10,44,956,74,0.374,0.315,2020
5,ロッテ,0.235,120,4505,3840,461,902,171,11,90,...,96,19,491,16,58,954,80,0.355,0.329,2020

In [12]:
# 2020セ

url_20c = 'https://npb.jp/bis/2020/stats/tmb_c.html'
df_20c = pd.read_html(url_20c)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_20c['年度'] = 2020

# 確認
df_20c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,DeNA,0.266,120,4501,4058,516,1078,180,10,135,...,51,26,337,15,29,867,94,0.415,0.324,2020
1,広 島,0.262,120,4609,4082,523,1069,198,21,110,...,81,17,386,27,43,890,91,0.402,0.331,2020
2,巨 人,0.255,120,4519,3994,532,1019,183,16,135,...,59,21,423,31,22,974,80,0.410,0.328,2020
3,中 日,0.252,120,4437,3952,429,997,178,18,70,...,73,27,346,24,39,812,101,0.360,0.317,2020
4,阪 神,0.246,120,4475,3923,494,965,167,17,110,...,86,23,400,25,43,955,83,0.381,0.321,2020
5,ヤクルト,0.242,120,4552,3994,468,967,163,13,114,...,56,26,434,30,42,931,95,0.375,0.321,2020

In [13]:
# 20年結合
df_20 = pd.concat([df_20p, df_20c], axis=0, ignore_index=True)
df_20

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,楽 天,0.258,120,4628,3990,557,1029,190,23,112,...,87,30,473,9,48,918,87,0.401,0.341,2020
1,日本ハム,0.249,120,4560,3952,493,986,153,17,89,...,85,31,460,9,32,878,86,0.364,0.330,2020
2,ソフトバンク,0.249,120,4480,3933,531,979,165,28,126,...,81,34,398,13,34,851,50,0.401,0.321,2020
3,オリックス,0.247,120,4467,3947,442,975,166,19,90,...,89,21,361,20,49,811,86,0.367,0.316,2020
4,西 武,0.238,120,4440,3898,479,926,161,24,107,...,60,27,411,10,44,956,74,0.374,0.315,2020
5,ロッテ,0.235,120,4505,3840,461,902,171,11,90,...,96,19,491,16,58,954,80,0.355,0.329,2020
6,DeNA,0.266,120,4501,4058,516,1078,180,10,135,...,51,26,337,15,29,867,94,0.415,0.324,2020
7,広 島,0.262,120,4609,4082,523,1069,198,21,110,...,81,17,386,27,43,890,91,0.402,0.331,2020
8,巨 人,0.255,120,4519,3994,532,1019,183,16,135,...,59,21,423,31,22,974,80,0.410,0.328,2020
9,中 日,0.252,120,4437,3952,429,997,178,18,70,...,73,27,346,24,39,812,101,0.360,0.317,2020
10,阪 神,0.246,120,4475,3923,494,965,167,17,110,...,86,23,400,25,43,955,83,0.381,0.321,2020
11,ヤクルト,0.242,120,4552,3994,468,967,163,13,114,...,56,26,434,30,42,931,95,0.375,0.321,2020

In [14]:
# 2019パ

url_19p = 'https://npb.jp/bis/2019/stats/tmb_p.html'
df_19p = pd.read_html(url_19p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_19p['年度'] = 2019

# 確認
df_19p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,西 武,0.265,143,5619,4898,756,1299,229,23,174,...,78,38,556,23,49,1083,88,0.428,0.344,2019
1,日本ハム,0.251,143,5428,4778,560,1200,211,28,93,...,78,33,496,18,43,1044,106,0.365,0.325,2019
2,ソフトバンク,0.251,143,5345,4775,582,1199,172,19,183,...,100,30,397,21,43,1084,85,0.410,0.312,2019
3,楽 天,0.251,143,5506,4766,614,1196,195,22,141,...,98,35,539,19,68,1127,114,0.390,0.333,2019
4,ロッテ,0.249,143,5503,4789,642,1194,214,21,158,...,92,29,505,12,87,1013,99,0.402,0.330,2019
5,オリックス,0.242,143,5391,4774,544,1153,181,22,102,...,101,33,417,17,66,1030,85,0.353,0.309,2019

In [15]:
# 2019セ

url_19c = 'https://npb.jp/bis/2019/stats/tmb_c.html'
df_19c = pd.read_html(url_19c)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_19c['年度'] = 2019

# 確認
df_19c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,中 日,0.263,143,5350,4816,563,1265,240,31,90,...,108,29,349,34,48,1024,104,0.381,0.317,2019
1,巨 人,0.257,143,5537,4835,663,1242,221,15,183,...,84,31,540,24,47,1205,106,0.422,0.335,2019
2,広 島,0.254,143,5504,4852,591,1232,216,17,140,...,111,26,479,40,36,1106,86,0.392,0.324,2019
3,阪 神,0.251,143,5465,4835,538,1213,216,20,94,...,104,30,447,32,49,1044,102,0.362,0.319,2019
4,DeNA,0.246,143,5375,4778,596,1177,210,14,163,...,81,26,449,31,41,1065,109,0.398,0.315,2019
5,ヤクルト,0.244,143,5572,4833,656,1181,205,19,167,...,84,29,570,29,56,1212,105,0.398,0.329,2019

In [16]:
# 19年結合
df_19 = pd.concat([df_19p, df_19c], axis=0, ignore_index=True)
df_19

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,西 武,0.265,143,5619,4898,756,1299,229,23,174,...,78,38,556,23,49,1083,88,0.428,0.344,2019
1,日本ハム,0.251,143,5428,4778,560,1200,211,28,93,...,78,33,496,18,43,1044,106,0.365,0.325,2019
2,ソフトバンク,0.251,143,5345,4775,582,1199,172,19,183,...,100,30,397,21,43,1084,85,0.410,0.312,2019
3,楽 天,0.251,143,5506,4766,614,1196,195,22,141,...,98,35,539,19,68,1127,114,0.390,0.333,2019
4,ロッテ,0.249,143,5503,4789,642,1194,214,21,158,...,92,29,505,12,87,1013,99,0.402,0.330,2019
5,オリックス,0.242,143,5391,4774,544,1153,181,22,102,...,101,33,417,17,66,1030,85,0.353,0.309,2019
6,中 日,0.263,143,5350,4816,563,1265,240,31,90,...,108,29,349,34,48,1024,104,0.381,0.317,2019
7,巨 人,0.257,143,5537,4835,663,1242,221,15,183,...,84,31,540,24,47,1205,106,0.422,0.335,2019
8,広 島,0.254,143,5504,4852,591,1232,216,17,140,...,111,26,479,40,36,1106,86,0.392,0.324,2019
9,阪 神,0.251,143,5465,4835,538,1213,216,20,94,...,104,30,447,32,49,1044,102,0.362,0.319,2019
10,DeNA,0.246,143,5375,4778,596,1177,210,14,163,...,81,26,449,31,41,1065,109,0.398,0.315,2019
11,ヤクルト,0.244,143,5572,4833,656,1181,205,19,167,...,84,29,570,29,56,1212,105,0.398,0.329,2019

In [17]:
# 2018パ

url_18p = 'https://npb.jp/bis/2018/stats/tmb_p.html'
df_18p = pd.read_html(url_18p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_18p['年度'] = 2018

# 確認
df_18p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,西 武,0.273,143,5638,4941,792,1351,244,29,196,...,48,33,566,14,50,1103,79,0.454,0.352,2018
1,ソフトバンク,0.266,143,5445,4855,685,1290,217,39,202,...,102,36,408,26,44,999,85,0.451,0.326,2018
2,日本ハム,0.251,143,5450,4759,589,1195,204,25,140,...,86,35,512,18,58,1101,109,0.393,0.329,2018
3,ロッテ,0.247,143,5412,4700,534,1159,207,35,78,...,108,43,474,12,86,888,93,0.355,0.324,2018
4,オリックス,0.244,143,5373,4766,538,1162,204,25,108,...,118,34,396,24,59,1003,98,0.365,0.308,2018
5,楽 天,0.241,143,5394,4824,520,1163,166,25,132,...,76,23,428,23,42,1074,109,0.368,0.307,2018

In [18]:
# 2018セ

url_18c = 'https://npb.jp/bis/2018/stats/tmb_c.html'
df_18c = pd.read_html(url_18c)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_18c['年度'] = 2018

# 確認
df_18c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,ヤクルト,0.266,143,5582,4836,658,1287,220,17,135,...,109,26,561,30,50,931,112,0.402,0.347,2018
1,中 日,0.265,143,5431,4858,598,1288,213,28,97,...,86,40,402,30,45,981,105,0.380,0.325,2018
2,広 島,0.262,143,5663,4858,721,1275,227,34,175,...,109,34,599,39,63,1143,85,0.431,0.349,2018
3,巨 人,0.257,143,5486,4878,625,1255,223,17,152,...,96,15,465,30,32,1120,100,0.403,0.325,2018
4,阪 神,0.253,143,5553,4833,577,1221,225,23,85,...,108,37,528,18,46,1086,109,0.361,0.330,2018
5,DeNA,0.250,143,5344,4837,572,1209,227,13,181,...,71,24,363,21,49,1041,91,0.415,0.307,2018

In [19]:
# 18年結合
df_18 = pd.concat([df_18p, df_18c], axis=0, ignore_index=True)
df_18

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,西 武,0.273,143,5638,4941,792,1351,244,29,196,...,48,33,566,14,50,1103,79,0.454,0.352,2018
1,ソフトバンク,0.266,143,5445,4855,685,1290,217,39,202,...,102,36,408,26,44,999,85,0.451,0.326,2018
2,日本ハム,0.251,143,5450,4759,589,1195,204,25,140,...,86,35,512,18,58,1101,109,0.393,0.329,2018
3,ロッテ,0.247,143,5412,4700,534,1159,207,35,78,...,108,43,474,12,86,888,93,0.355,0.324,2018
4,オリックス,0.244,143,5373,4766,538,1162,204,25,108,...,118,34,396,24,59,1003,98,0.365,0.308,2018
5,楽 天,0.241,143,5394,4824,520,1163,166,25,132,...,76,23,428,23,42,1074,109,0.368,0.307,2018
6,ヤクルト,0.266,143,5582,4836,658,1287,220,17,135,...,109,26,561,30,50,931,112,0.402,0.347,2018
7,中 日,0.265,143,5431,4858,598,1288,213,28,97,...,86,40,402,30,45,981,105,0.380,0.325,2018
8,広 島,0.262,143,5663,4858,721,1275,227,34,175,...,109,34,599,39,63,1143,85,0.431,0.349,2018
9,巨 人,0.257,143,5486,4878,625,1255,223,17,152,...,96,15,465,30,32,1120,100,0.403,0.325,2018
10,阪 神,0.253,143,5553,4833,577,1221,225,23,85,...,108,37,528,18,46,1086,109,0.361,0.330,2018
11,DeNA,0.250,143,5344,4837,572,1209,227,13,181,...,71,24,363,21,49,1041,91,0.415,0.307,2018

In [20]:
# 2017パ

url_17p = 'https://npb.jp/bis/2017/stats/tmb_p.html'
df_17p = pd.read_html(url_17p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_17p['年度'] = 2017

# 確認
df_17p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,西 武,0.264,143,5445,4792,690,1264,236,28,153,...,93,45,457,4,58,1029,95,0.420,0.332,2017
1,ソフトバンク,0.259,143,5382,4671,638,1208,202,32,164,...,156,31,488,16,36,1019,78,0.421,0.331,2017
2,楽 天,0.254,143,5452,4812,585,1221,214,18,135,...,105,22,473,10,40,1018,107,0.390,0.324,2017
3,オリックス,0.251,143,5411,4770,539,1197,190,23,127,...,149,26,409,6,57,1032,105,0.380,0.316,2017
4,日本ハム,0.242,143,5385,4749,509,1147,189,18,108,...,103,28,468,2,37,1122,95,0.357,0.313,2017
5,ロッテ,0.233,143,5286,4718,479,1098,215,29,95,...,98,26,387,8,57,1099,85,0.351,0.297,2017

In [21]:
# 2017セ

url_17c = 'https://npb.jp/bis/2017/stats/tmb_c.html'
df_17c = pd.read_html(url_17c)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_17c['年度'] = 2017

# 確認
df_17c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,広 島,0.273,143,5592,4872,736,1329,237,23,152,...,116,44,511,4,49,1114,95,0.424,0.345,2017
1,DeNA,0.252,143,5402,4872,597,1230,245,14,134,...,84,22,378,6,46,1091,101,0.391,0.311,2017
2,巨 人,0.249,143,5384,4775,536,1190,223,15,113,...,87,27,452,15,43,1006,129,0.373,0.318,2017
3,阪 神,0.249,143,5520,4807,589,1195,213,18,113,...,113,26,531,10,43,1008,97,0.371,0.327,2017
4,中 日,0.247,143,5306,4794,487,1183,190,23,111,...,115,21,320,4,56,1103,86,0.365,0.300,2017
5,ヤクルト,0.234,143,5358,4728,473,1108,166,19,95,...,109,20,454,5,44,1013,116,0.338,0.306,2017

In [22]:
# 17年結合
df_17 = pd.concat([df_17p, df_17c], axis=0, ignore_index=True)
df_17

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,西 武,0.264,143,5445,4792,690,1264,236,28,153,...,93,45,457,4,58,1029,95,0.420,0.332,2017
1,ソフトバンク,0.259,143,5382,4671,638,1208,202,32,164,...,156,31,488,16,36,1019,78,0.421,0.331,2017
2,楽 天,0.254,143,5452,4812,585,1221,214,18,135,...,105,22,473,10,40,1018,107,0.390,0.324,2017
3,オリックス,0.251,143,5411,4770,539,1197,190,23,127,...,149,26,409,6,57,1032,105,0.380,0.316,2017
4,日本ハム,0.242,143,5385,4749,509,1147,189,18,108,...,103,28,468,2,37,1122,95,0.357,0.313,2017
5,ロッテ,0.233,143,5286,4718,479,1098,215,29,95,...,98,26,387,8,57,1099,85,0.351,0.297,2017
6,広 島,0.273,143,5592,4872,736,1329,237,23,152,...,116,44,511,4,49,1114,95,0.424,0.345,2017
7,DeNA,0.252,143,5402,4872,597,1230,245,14,134,...,84,22,378,6,46,1091,101,0.391,0.311,2017
8,巨 人,0.249,143,5384,4775,536,1190,223,15,113,...,87,27,452,15,43,1006,129,0.373,0.318,2017
9,阪 神,0.249,143,5520,4807,589,1195,213,18,113,...,113,26,531,10,43,1008,97,0.371,0.327,2017
10,中 日,0.247,143,5306,4794,487,1183,190,23,111,...,115,21,320,4,56,1103,86,0.365,0.300,2017
11,ヤクルト,0.234,143,5358,4728,473,1108,166,19,95,...,109,20,454,5,44,1013,116,0.338,0.306,2017

In [23]:
# 2016パ

url_16p = 'https://npb.jp/bis/2016/stats/tmb_p.html'
df_16p = pd.read_html(url_16p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_16p['年度'] = 2016

# 確認
df_16p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,日本ハム,0.266,143,5550,4795,619,1277,179,13,121,...,178,28,496,10,53,1076,79,0.385,0.340,2016
1,西 武,0.264,143,5536,4881,619,1287,219,19,128,...,80,36,493,7,46,1071,97,0.395,0.335,2016
2,ソフトバンク,0.261,143,5526,4744,637,1240,188,30,114,...,148,40,537,14,57,956,110,0.386,0.341,2016
3,楽 天,0.257,143,5441,4806,544,1234,170,32,101,...,122,26,439,10,48,952,112,0.368,0.324,2016
4,ロッテ,0.256,143,5483,4810,583,1230,216,30,80,...,120,34,461,14,58,964,102,0.363,0.326,2016
5,オリックス,0.253,143,5382,4747,499,1199,208,12,84,...,154,25,399,12,57,910,93,0.355,0.317,2016

In [24]:
# 2016セ

url_16c = 'https://npb.jp/bis/2016/stats/tmb_c.html'
df_16c = pd.read_html(url_16c)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_16c['年度'] = 2016

# 確認
df_16c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,広 島,0.272,143,5582,4914,684,1338,203,35,153,...,91,29,500,13,47,1063,85,0.421,0.343,2016
1,ヤクルト,0.256,143,5509,4828,594,1234,210,20,113,...,85,33,524,10,39,907,117,0.378,0.331,2016
2,巨 人,0.251,143,5356,4797,519,1203,217,19,128,...,112,23,389,11,35,961,100,0.384,0.310,2016
3,DeNA,0.249,143,5364,4838,572,1205,194,21,140,...,81,18,373,7,54,1049,92,0.385,0.309,2016
4,中 日,0.245,143,5405,4813,500,1180,209,21,89,...,108,28,410,7,46,1001,103,0.353,0.309,2016
5,阪 神,0.245,143,5401,4789,506,1171,204,17,90,...,88,38,435,17,51,1149,99,0.351,0.312,2016

In [25]:
# 16年結合
df_16 = pd.concat([df_16p, df_16c], axis=0, ignore_index=True)
df_16

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,日本ハム,0.266,143,5550,4795,619,1277,179,13,121,...,178,28,496,10,53,1076,79,0.385,0.340,2016
1,西 武,0.264,143,5536,4881,619,1287,219,19,128,...,80,36,493,7,46,1071,97,0.395,0.335,2016
2,ソフトバンク,0.261,143,5526,4744,637,1240,188,30,114,...,148,40,537,14,57,956,110,0.386,0.341,2016
3,楽 天,0.257,143,5441,4806,544,1234,170,32,101,...,122,26,439,10,48,952,112,0.368,0.324,2016
4,ロッテ,0.256,143,5483,4810,583,1230,216,30,80,...,120,34,461,14,58,964,102,0.363,0.326,2016
5,オリックス,0.253,143,5382,4747,499,1199,208,12,84,...,154,25,399,12,57,910,93,0.355,0.317,2016
6,広 島,0.272,143,5582,4914,684,1338,203,35,153,...,91,29,500,13,47,1063,85,0.421,0.343,2016
7,ヤクルト,0.256,143,5509,4828,594,1234,210,20,113,...,85,33,524,10,39,907,117,0.378,0.331,2016
8,巨 人,0.251,143,5356,4797,519,1203,217,19,128,...,112,23,389,11,35,961,100,0.384,0.310,2016
9,DeNA,0.249,143,5364,4838,572,1205,194,21,140,...,81,18,373,7,54,1049,92,0.385,0.309,2016
10,中 日,0.245,143,5405,4813,500,1180,209,21,89,...,108,28,410,7,46,1001,103,0.353,0.309,2016
11,阪 神,0.245,143,5401,4789,506,1171,204,17,90,...,88,38,435,17,51,1149,99,0.351,0.312,2016

In [26]:
# 2015パ

url_15p = 'https://npb.jp/bis/2015/stats/tmb_p.html'
df_15p = pd.read_html(url_15p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_15p['年度'] = 2015

# 確認
df_15p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,ソフトバンク,0.267,143,5559,4852,651,1294,217,22,141,...,109,40,507,14,51,950,110,0.408,0.340,2015
1,西 武,0.263,143,5497,4818,631,1265,243,21,136,...,104,30,480,11,64,1194,84,0.406,0.335,2015
2,日本ハム,0.258,143,5469,4802,615,1238,205,27,106,...,104,30,487,10,46,1031,90,0.378,0.330,2015
3,ロッテ,0.257,143,5362,4767,561,1227,203,34,85,...,109,32,410,6,44,858,95,0.368,0.320,2015
4,オリックス,0.249,143,5380,4725,519,1175,184,16,94,...,115,27,446,7,67,923,86,0.354,0.321,2015
5,楽 天,0.241,143,5423,4777,463,1150,180,16,85,...,105,35,445,10,61,926,96,0.338,0.311,2015

In [27]:
# 2015セ

url_15c = 'https://npb.jp/bis/2015/stats/tmb_c.html'
df_15c = pd.read_html(url_15c)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_15c['年度'] = 2015

# 確認
df_15c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,ヤクルト,0.257,143,5423,4817,574,1240,223,16,107,...,104,31,433,4,37,909,96,0.377,0.322,2015
1,中 日,0.253,143,5414,4835,473,1222,188,19,71,...,114,27,401,10,36,1000,83,0.344,0.313,2015
2,DeNA,0.249,143,5328,4763,508,1186,219,18,112,...,137,24,361,7,43,1047,77,0.373,0.306,2015
3,阪 神,0.247,143,5373,4705,465,1160,192,15,78,...,138,28,464,9,38,1001,93,0.343,0.317,2015
4,広 島,0.246,143,5386,4752,506,1170,201,32,105,...,135,29,441,12,29,1082,87,0.368,0.312,2015
5,巨 人,0.243,143,5304,4672,489,1137,190,16,98,...,116,30,434,6,52,974,92,0.354,0.313,2015

In [28]:
# 15年結合
df_15 = pd.concat([df_15p, df_15c], axis=0, ignore_index=True)
df_15

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,ソフトバンク,0.267,143,5559,4852,651,1294,217,22,141,...,109,40,507,14,51,950,110,0.408,0.340,2015
1,西 武,0.263,143,5497,4818,631,1265,243,21,136,...,104,30,480,11,64,1194,84,0.406,0.335,2015
2,日本ハム,0.258,143,5469,4802,615,1238,205,27,106,...,104,30,487,10,46,1031,90,0.378,0.330,2015
3,ロッテ,0.257,143,5362,4767,561,1227,203,34,85,...,109,32,410,6,44,858,95,0.368,0.320,2015
4,オリックス,0.249,143,5380,4725,519,1175,184,16,94,...,115,27,446,7,67,923,86,0.354,0.321,2015
5,楽 天,0.241,143,5423,4777,463,1150,180,16,85,...,105,35,445,10,61,926,96,0.338,0.311,2015
6,ヤクルト,0.257,143,5423,4817,574,1240,223,16,107,...,104,31,433,4,37,909,96,0.377,0.322,2015
7,中 日,0.253,143,5414,4835,473,1222,188,19,71,...,114,27,401,10,36,1000,83,0.344,0.313,2015
8,DeNA,0.249,143,5328,4763,508,1186,219,18,112,...,137,24,361,7,43,1047,77,0.373,0.306,2015
9,阪 神,0.247,143,5373,4705,465,1160,192,15,78,...,138,28,464,9,38,1001,93,0.343,0.317,2015
10,広 島,0.246,143,5386,4752,506,1170,201,32,105,...,135,29,441,12,29,1082,87,0.368,0.312,2015
11,巨 人,0.243,143,5304,4672,489,1137,190,16,98,...,116,30,434,6,52,974,92,0.354,0.313,2015

In [29]:
# 2014パ

url_14p = 'https://npb.jp/bis/2014/stats/tmb_p.html'
df_14p = pd.read_html(url_14p)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_14p['年度'] = 2014

# 確認
df_14p

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,ソフトバンク,0.280,144,5631,4935,607,1383,227,30,95,...,146,47,444,21,59,921,96,0.396,0.344,2014
1,オリックス,0.258,144,5469,4710,584,1215,211,22,110,...,177,27,470,20,85,907,91,0.382,0.334,2014
2,楽 天,0.255,144,5455,4768,549,1214,215,18,78,...,118,36,488,9,45,959,119,0.356,0.327,2014
3,日本ハム,0.251,144,5428,4731,593,1188,188,29,119,...,172,26,452,8,47,1092,72,0.379,0.321,2014
4,ロッテ,0.251,144,5433,4836,556,1213,260,33,96,...,109,31,404,7,53,862,79,0.378,0.314,2014
5,西 武,0.248,144,5563,4782,574,1187,221,26,125,...,155,36,545,8,45,1234,81,0.384,0.329,2014

In [30]:
# 2014セ

url_14c = 'https://npb.jp/bis/2014/stats/tmb_c.html'
df_14c = pd.read_html(url_14c)[0]

# 年度の列を追加（後で他の年度と結合するので）
df_14c['年度'] = 2014

# 確認
df_14c

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,ヤクルト,0.279,144,5653,5023,667,1401,223,15,139,...,118,34,443,12,35,877,112,0.412,0.339,2014
1,広 島,0.272,144,5538,4878,649,1326,219,23,153,...,120,40,450,20,50,1134,104,0.420,0.337,2014
2,阪 神,0.264,144,5507,4823,599,1274,226,15,94,...,121,35,483,16,45,1009,124,0.376,0.335,2014
3,中 日,0.258,144,5521,4854,570,1250,215,21,87,...,126,40,467,12,34,926,109,0.364,0.325,2014
4,巨 人,0.257,144,5480,4862,596,1248,207,7,144,...,117,28,419,11,54,923,124,0.391,0.321,2014
5,DeNA,0.253,144,5464,4833,568,1224,211,27,121,...,149,21,400,23,61,1107,110,0.383,0.317,2014

In [31]:
# 14年結合
df_14 = pd.concat([df_14p, df_14c], axis=0, ignore_index=True)
df_14

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,ソフトバンク,0.280,144,5631,4935,607,1383,227,30,95,...,146,47,444,21,59,921,96,0.396,0.344,2014
1,オリックス,0.258,144,5469,4710,584,1215,211,22,110,...,177,27,470,20,85,907,91,0.382,0.334,2014
2,楽 天,0.255,144,5455,4768,549,1214,215,18,78,...,118,36,488,9,45,959,119,0.356,0.327,2014
3,日本ハム,0.251,144,5428,4731,593,1188,188,29,119,...,172,26,452,8,47,1092,72,0.379,0.321,2014
4,ロッテ,0.251,144,5433,4836,556,1213,260,33,96,...,109,31,404,7,53,862,79,0.378,0.314,2014
5,西 武,0.248,144,5563,4782,574,1187,221,26,125,...,155,36,545,8,45,1234,81,0.384,0.329,2014
6,ヤクルト,0.279,144,5653,5023,667,1401,223,15,139,...,118,34,443,12,35,877,112,0.412,0.339,2014
7,広 島,0.272,144,5538,4878,649,1326,219,23,153,...,120,40,450,20,50,1134,104,0.420,0.337,2014
8,阪 神,0.264,144,5507,4823,599,1274,226,15,94,...,121,35,483,16,45,1009,124,0.376,0.335,2014
9,中 日,0.258,144,5521,4854,570,1250,215,21,87,...,126,40,467,12,34,926,109,0.364,0.325,2014
10,巨 人,0.257,144,5480,4862,596,1248,207,7,144,...,117,28,419,11,54,923,124,0.391,0.321,2014
11,DeNA,0.253,144,5464,4833,568,1224,211,27,121,...,149,21,400,23,61,1107,110,0.383,0.317,2014

In [32]:
# 14年～23年を縦に結合

df_10y = pd.concat(
    [df_23, df_22, df_21, df_20, df_19, df_18, df_17, df_16, df_15, df_14],
    axis=0,
    ignore_index=True
)

# 行列数確認
df_10y.shape

(120, 24)

In [33]:
# csvファイルに出力
df_10y.to_csv('team_batting_14_23.csv', 
              index=False)

In [34]:
# データ読み込みして確認
df_new = pd.read_csv('team_batting_14_23.csv')
df_new.shape

(120, 24)

In [35]:
df_new.head(10)

,チーム,打 率,試 合,打 席,打 数,得 点,安 打,二 塁 打,三 塁 打,本 塁 打,...,犠 打,犠 飛,四 球,故 意 四,死 球,三 振,併 殺 打,長 打 率,出 塁 率,年度
0,オリックス,0.250,143,5324,4782,508,1194,211,17,109,...,83,25,371,8,63,986,106,0.369,0.311,2023
1,ソフトバンク,0.248,143,5454,4786,536,1185,195,15,104,...,107,38,470,14,53,1053,88,0.360,0.319,2023
2,楽 天,0.244,143,5369,4667,513,1140,168,25,104,...,125,33,490,9,52,937,108,0.358,0.321,2023
3,ロッテ,0.239,143,5414,4744,505,1135,220,12,100,...,116,39,453,20,62,1011,79,0.354,0.311,2023
4,西 武,0.233,143,5222,4672,435,1088,188,21,90,...,90,28,387,9,45,1045,97,0.340,0.296,2023
5,日本ハム,0.231,143,5248,4688,464,1082,195,18,100,...,84,25,397,10,54,1111,78,0.344,0.297,2023
6,巨 人,0.252,143,5352,4826,523,1218,204,14,164,...,93,31,365,38,37,1111,94,0.402,0.308,2023
7,DeNA,0.247,143,5331,4783,520,1182,230,18,105,...,106,31,355,22,56,846,103,0.369,0.305,2023
8,阪 神,0.247,143,5479,4775,555,1180,179,34,84,...,106,47,494,35,57,1173,92,0.352,0.322,2023
9,広 島,0.246,143,5241,4728,493,1165,197,18,96,...,96,20,349,25,48,1032,115,0.357,0.304,2023